import { Publisher } from '../types';

// Valores padrão para novos campos, garantindo a consistência.
const defaultAvailability = { mode: 'always' as const, exceptionDates: [] };
const defaultNewFields = { ageGroup: 'Adulto' as const, parentIds: [], isHelperOnly: false, canPairWithNonParent: false };

// Helper para criar um objeto de privilégios de irmão com base nos 'ok' da tabela
const createBrotherPrivileges = (canRead: boolean, canGiveTalks: boolean, canPray: boolean, canPreside: boolean) => ({
    canGiveTalks,
    canConductCBS: canPreside, // Apenas anciãos podem dirigir o EBC
    canReadCBS: canRead,
    canPray,
    canPreside,
});

// Lista de publicadores extraída da "Avaliação dos Varões" e outras listas.
export const initialPublishers: Publisher[] = [
    // ANCIÃOS
    {
        id: 'anc1', name: 'Diego Fontana', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'anc2', name: 'Domingos Oliveira', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'anc3', name: 'Edmardo Queiroz', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'anc4', name: 'Edmilson Monteiro', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'anc5', name: 'Eliezer Rosa', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'anc6', name: 'Israel Vieira', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'anc7', name: 'José Luiz Fouraux', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'anc8', name: 'Marcos Rogério', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'anc9', name: 'Marcos Vinícios', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'anc10', name: 'Renato Oliveira', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'anc11', name: 'Mario Porto', gender: 'brother', condition: 'Ancião', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, true),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: ['Mário Porto']
    },

    // SERVO MINISTERIAIS
    {
        id: 'sm1', name: 'Alexsandro Lopes', gender: 'brother', condition: 'Servo Ministerial', phone: '27996528686', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, false), // SMs não presidem
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'sm2', name: 'Daniel Silva', gender: 'brother', condition: 'Servo Ministerial', phone: '27996952195', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(false, false, false, false),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'sm3', name: 'Emerson Souza', gender: 'brother', condition: 'Servo Ministerial', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(false, false, false, false),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'sm4', name: 'Felipe Oliveira', gender: 'brother', condition: 'Servo Ministerial', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, false, true, false),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'sm5', name: 'Samuel Almeida', gender: 'brother', condition: 'Servo Ministerial', phone: '27996245928', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, false),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'sm6', name: 'Patrick Oliveira', gender: 'brother', condition: 'Servo Ministerial', phone: '', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, false, true, false),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },
    {
        id: 'sm7', name: 'Júnior Fouraux', gender: 'brother', condition: 'Servo Ministerial', phone: '27992989988', isBaptized: true, isServing: true, ...defaultNewFields,
        privileges: createBrotherPrivileges(true, true, true, false),
        privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true },
        availability: defaultAvailability, aliases: []
    },

    // IRMÃOS (ESCOLA)
    { id: 'bro1', name: 'Carlos Ramos', gender: 'brother', condition: 'Publicador', phone: '27981781342', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro2', name: 'Diego Resmann', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, true, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro3', name: 'Antônio Miguel', gender: 'brother', condition: 'Publicador', phone: '27992928631', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro4', name: 'Eryck Segal', gender: 'brother', condition: 'Publicador', phone: '27995125833', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, true, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: ['Erick José'] },
    { id: 'bro5', name: 'Fernando Pessoa', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, true, true, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro6', name: 'Victor Correa', gender: 'brother', condition: 'Publicador', phone: '27998205347', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, true, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro7', name: 'Antônio Garcia', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: false, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'bro8', name: 'Antônio Nascimento', gender: 'brother', condition: 'Publicador', phone: '27981119805', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, true, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro9', name: 'Daniel Figueiredo', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, true, true, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro10', name: 'André Luiz', gender: 'brother', condition: 'Publicador', phone: '27998447126', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, true, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro11', name: 'João Mendes', gender: 'brother', condition: 'Publicador', phone: '27998956799', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, true, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro12', name: 'Emerson França', gender: 'brother', condition: 'Publicador', phone: '27996133137', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, true, true, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro13', name: 'Carlos Augusto', gender: 'brother', condition: 'Publicador', phone: '27988647171', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro14', name: 'Gabriel Camilo', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, true, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro15', name: 'Mauro Rezende', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro16', name: 'Luiz Alexandrino', gender: 'brother', condition: 'Publicador', phone: '27988055100', isBaptized: false, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'bro17', name: 'Luiz Gustavo Rangel', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, true, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro18', name: 'Edmilson Pessanha', gender: 'brother', condition: 'Publicador', phone: '27999704928', isBaptized: false, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'bro19', name: 'Vitor Pessanha', gender: 'brother', condition: 'Publicador', phone: '27997266591', isBaptized: false, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'bro20', name: 'Vinicius Pessanha', gender: 'brother', condition: 'Publicador', phone: '27995904437', isBaptized: false, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'bro21', name: 'Fernando Balieira', gender: 'brother', condition: 'Publicador', phone: '27981018424', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro22', name: 'Gerson Ribeiro dos Santos', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(true, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro23', name: 'Cláudio Vieira', gender: 'brother', condition: 'Publicador', phone: '27998424152', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro24', name: 'Patrick de Oliveira', gender: 'brother', condition: 'Publicador', phone: '27999598949', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro25', name: 'Gabriel Fouraux', gender: 'brother', condition: 'Publicador', phone: '27992388157', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro26', name: 'Gustavo Rangel', gender: 'brother', condition: 'Publicador', phone: '27999795638', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro27', name: 'Gérson Santos', gender: 'brother', condition: 'Publicador', phone: '71984798864', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro28', name: 'Daniel Carneiro', gender: 'brother', condition: 'Publicador', phone: '27999393340', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro29', name: 'Felipe de Oliveira', gender: 'brother', condition: 'Publicador', phone: '27999421370', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'bro30', name: 'Saymon Schultz', gender: 'brother', condition: 'Publicador', phone: '27992473651', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    
    // IRMÃS (ESCOLA) - Todas com `aliases: []`
    { id: 'sis1', name: 'Ana Paula Oliveira', gender: 'sister', condition: 'Publicador', phone: '27993098093', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis2', name: 'Ariane Bello', gender: 'sister', condition: 'Publicador', phone: '27998353014', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis3', name: 'Ágatha do Nascimento', gender: 'sister', condition: 'Publicador', phone: '27992880526', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis4', name: 'Dayse Campos', gender: 'sister', condition: 'Publicador', phone: '27992846954', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis5', name: 'Débora Cristine', gender: 'sister', condition: 'Publicador', phone: '27995312445', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis6', name: 'Érika Segall', gender: 'sister', condition: 'Publicador', phone: '27999727739', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis7', name: 'Elina Mendes', gender: 'sister', condition: 'Publicador', phone: '6186222151', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis8', name: 'Edna Costa dos Santos', gender: 'sister', condition: 'Publicador', phone: '27988117244', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis9', name: 'Eliana Souza', gender: 'sister', condition: 'Publicador', phone: '27981296551', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis10', name: 'Elza Elena', gender: 'sister', condition: 'Publicador', phone: '27997976498', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis11', name: 'Geysa Nascimento', gender: 'sister', condition: 'Publicador', phone: '27992934687', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis12', name: 'Gérbera Nascimento', gender: 'sister', condition: 'Publicador', phone: '27992453895', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis13', name: 'Inêz Monteiro', gender: 'sister', condition: 'Publicador', phone: '27997935590', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis14', name: 'Ivone Balieira', gender: 'sister', condition: 'Publicador', phone: '21965389404', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis15', name: 'Isabelle Cruz', gender: 'sister', condition: 'Publicador', phone: '27998395719', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis16', name: 'Jacyra Eugênio', gender: 'sister', condition: 'Publicador', phone: '27988131290', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis17', name: 'Josyane Vieira', gender: 'sister', condition: 'Publicador', phone: '27998098099', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis18', name: 'Julianne Cravo Figueredo', gender: 'sister', condition: 'Publicador', phone: '27998214512', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis19', name: 'Keyla Costa', gender: 'sister', condition: 'Publicador', phone: '27988492005', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis20', name: 'Larissa Queiroz', gender: 'sister', condition: 'Publicador', phone: '27997795605', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis21', name: 'Luciana Marques', gender: 'sister', condition: 'Publicador', phone: '27992371244', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis22', name: 'Luciana Alves', gender: 'sister', condition: 'Publicador', phone: '3193949672', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis23', name: 'Mylena Balieira', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis24', name: 'Maria de Lourdes', gender: 'sister', condition: 'Publicador', phone: '27992473651', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis25', name: 'Marcela Resmann', gender: 'sister', condition: 'Publicador', phone: '27997371276', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis26', name: 'Maria Izabel', gender: 'sister', condition: 'Publicador', phone: '27995270049', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis27', name: 'Márcia Rosa', gender: 'sister', condition: 'Publicador', phone: '27981170400', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis28', name: 'Márcia Bragança', gender: 'sister', condition: 'Publicador', phone: '27997943143', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis29', name: 'Margarete Venturin', gender: 'sister', condition: 'Publicador', phone: '27997924986', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis30', name: 'Mara Rúbia', gender: 'sister', condition: 'Publicador', phone: '27997338016', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis31', name: 'Marilene Queiroz', gender: 'sister', condition: 'Publicador', phone: '28999736468', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis32', name: 'Malena Colangero', gender: 'sister', condition: 'Publicador', phone: '27992641214', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis33', name: 'Michele Camillo', gender: 'sister', condition: 'Publicador', phone: '27981361505', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis34', name: 'Nazaré de Lima', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis35', name: 'Nanci Celia', gender: 'sister', condition: 'Publicador', phone: '21986844383', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis36', name: 'Neuza Campanha', gender: 'sister', condition: 'Publicador', phone: '27998313861', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis37', name: 'Priscila', gender: 'sister', condition: 'Publicador', phone: '8192919973', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis38', name: 'Raquel Oliveira', gender: 'sister', condition: 'Publicador', phone: '27997806764', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis39', name: 'Reica Santana Ribeiro', gender: 'sister', condition: 'Publicador', phone: '27999216136', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis40', name: 'Rozelita Sales', gender: 'sister', condition: 'Publicador', phone: '27998595458', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis41', name: 'Sandra Duarte', gender: 'sister', condition: 'Publicador', phone: '27996600407', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis42', name: 'Suellen Correa', gender: 'sister', condition: 'Publicador', phone: '27997375030', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis43', name: 'Sirlene Ramos', gender: 'sister', condition: 'Publicador', phone: '27988388707', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis44', name: 'Yngrid França', gender: 'sister', condition: 'Publicador', phone: '27992654811', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis45', name: 'Terezinha Oliveira', gender: 'sister', condition: 'Publicador', phone: '27997657258', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis46', name: 'Vitoria Emanuelle', gender: 'sister', condition: 'Publicador', phone: '27920017006', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'sis47', name: 'Waleska Nascimento', gender: 'sister', condition: 'Publicador', phone: '27998931684', isBaptized: true, isServing: true, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: { mode: 'always', exceptionDates: ['2025-01-01', '2025-12-31'] }, aliases: [] },
    
    // NÃO ATUANTES - Todas com `aliases: []`
    { id: 'na1', name: 'Leonardo Barjona Colangero Nascimento', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'na2', name: 'Antônio Barjona Garcia Nascimento', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'na3', name: 'Eugenio Longo', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'na4', name: 'João Antonio', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'na5', name: 'Edmar', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'na6', name: 'Mauro Vieira', gender: 'brother', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: true, canParticipateInMinistry: true, canParticipateInLife: true }, availability: defaultAvailability, aliases: [] },
    { id: 'na7', name: 'Gerusa Souza', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na8', name: 'Brenda Cristine Cunha Pacheco', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na9', name: 'Auxiliadora Valéria Neves', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na10', name: 'Saniyuriss Bernardes dos Reis', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na11', name: 'Amanda Garcia Ferreira Nascimento', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na12', name: 'Tamiris Mendes', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na13', name: 'Marcela Gomes Coelho', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na14', name: 'Raquel Elvira', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na15', name: 'Edlena', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na16', name: 'Maria Helena Carvalho Santos', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na17', name: 'Maria Aparecida Cândida Marques', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na18', name: 'Maria Eduarda Marques Carone Reis', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na19', name: 'Maria José Farias', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na20', name: 'Yasmin Reis dos Santos', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na21', name: 'Lídia Ramos', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na22', name: 'Ivone Oliveira', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na23', name: 'Jeane Pinto Gomes', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na24', name: 'Rosa da Silva Miranda', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na25', name: 'Aila Rosana Porto', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na26', name: 'Aparecida Baldi', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na27', name: 'Maria José Tonon da Cruz', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na28', name: 'Melissa Rachel Porto Queiroz', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na29', name: 'Tânia Mendes', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na30', name: 'Solange Telles', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na31', name: 'Laramara Rosa Nascimento', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na32', name: 'Tatiana', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na33', name: 'Célia Regina Figueiredo', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na34', name: 'Olívia Maria Porto', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
    { id: 'na35', name: 'Iná Trancoso Gervásio', gender: 'sister', condition: 'Publicador', phone: '', isBaptized: true, isServing: false, ...defaultNewFields, privileges: createBrotherPrivileges(false, false, false, false), privilegesBySection: { canParticipateInTreasures: false, canParticipateInMinistry: true, canParticipateInLife: false }, availability: defaultAvailability, aliases: [] },
];