import { Participation, ParticipationType } from '../types';
import { generateUUID, calculatePartDate } from './utils';

const rawParticipations = [
  // NOVEMBRO 2024
  { publisherName: 'Eliezer Rosa', week: '4-10 de NOV, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Eliezer Rosa', week: '4-10 de NOV, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '4-10 de NOV, 2024', partTitle: 'Cântico 3', type: ParticipationType.CANTICO },
  { publisherName: 'Edmardo Queiroz', week: '4-10 de NOV, 2024', partTitle: '"Ele se lembra do seu pacto para sempre"', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Marcos Vinícios', week: '4-10 de NOV, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Samuel Almeida', week: '4-10 de NOV, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Rozelita Sales', week: '4-10 de NOV, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 1 },
  { publisherName: 'Keyla Costa', week: '4-10 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Yngrid França', week: '4-10 de NOV, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 2 },
  { publisherName: 'Wanderleia Santos', week: '4-10 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Suellen Correa', week: '4-10 de NOV, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Waleska Nascimento', week: '4-10 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Tainá Reis', week: '4-10 de NOV, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Vitoria Emanuelle', week: '4-10 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: '', week: '4-10 de NOV, 2024', partTitle: 'Cântico 84', type: ParticipationType.CANTICO },
  { publisherName: 'Marcos Rogério', week: '4-10 de NOV, 2024', partTitle: '"Demonstrações do nosso amor"', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Renato Oliveira', week: '4-10 de NOV, 2024', partTitle: 'Estudo bíblico de congregação', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Júnior Fouraux', week: '4-10 de NOV, 2024', partTitle: 'Leitor do EBC', type: ParticipationType.LEITOR },
  { publisherName: 'Eliezer Rosa', week: '4-10 de NOV, 2024', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '4-10 de NOV, 2024', partTitle: 'Cântico 97', type: ParticipationType.CANTICO },
  { publisherName: 'André Luiz', week: '4-10 de NOV, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },
  
  { publisherName: 'Domingos Oliveira', week: '11-17 de NOV, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Domingos Oliveira', week: '11-17 de NOV, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '11-17 de NOV, 2024', partTitle: 'Cântico 36', type: ParticipationType.CANTICO },
  { publisherName: 'Renato Oliveira', week: '11-17 de NOV, 2024', partTitle: '"Esqueceram-se de Deus, seu Salvador"', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Juberto Santos', week: '11-17 de NOV, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'André Luiz', week: '11-17 de NOV, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Emerson Souza', week: '11-17 de NOV, 2024', partTitle: 'Simplicidade — O que Jesus fez', type: ParticipationType.MINISTERIO, duration: 7 },
  { publisherName: 'Eliezer Rosa', week: '11-17 de NOV, 2024', partTitle: 'Simplicidade — Imite Jesus', type: ParticipationType.MINISTERIO, duration: 8 },
  { publisherName: '', week: '11-17 de NOV, 2024', partTitle: 'Cântico 78', type: ParticipationType.CANTICO },
  { publisherName: 'Israel Vieira', week: '11-17 de NOV, 2024', partTitle: 'Necessidades locais', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Domingos Oliveira', week: '11-17 de NOV, 2024', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '11-17 de NOV, 2024', partTitle: 'Cântico 77', type: ParticipationType.CANTICO },
  { publisherName: 'Israel Vieira', week: '11-17 de NOV, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Marcos Vinícios', week: '18-24 de NOV, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Marcos Vinícios', week: '18-24 de NOV, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '18-24 de NOV, 2024', partTitle: 'Cântico 7', type: ParticipationType.CANTICO },
  { publisherName: 'Eliezer Rosa', week: '18-24 de NOV, 2024', partTitle: '"Agradeçam a Jeová, pois ele é bom"', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Edmardo Queiroz', week: '18-24 de NOV, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Saymon Schultz', week: '18-24 de NOV, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Saniyuriss Reis', week: '18-24 de NOV, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Julianne Pereira', week: '18-24 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Josyane Vieira', week: '18-24 de NOV, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Jacyra Eugênio', week: '18-24 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Juberto Santos', week: '18-24 de NOV, 2024', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: '', week: '18-24 de NOV, 2024', partTitle: 'Cântico 46', type: ParticipationType.CANTICO },
  { publisherName: 'José Luiz Fouraux', week: '18-24 de NOV, 2024', partTitle: 'Cantamos para agradecer a Jeová', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Diego Fontana', week: '18-24 de NOV, 2024', partTitle: 'Estudo bíblico de congregação', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Carlos Ramos', week: '18-24 de NOV, 2024', partTitle: 'Leitor do EBC', type: ParticipationType.LEITOR },
  { publisherName: 'Marcos Vinícios', week: '18-24 de NOV, 2024', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '18-24 de NOV, 2024', partTitle: 'Cântico 73', type: ParticipationType.CANTICO },
  { publisherName: 'Juberto Santos', week: '18-24 de NOV, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Marcos Rogério', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Marcos Rogério', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Cântico 14', type: ParticipationType.CANTICO },
  { publisherName: 'Domingos Oliveira', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Apoie o Rei Jesus!', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Samuel Almeida', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Hidelmar Amorim', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Sandra Duarte', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 2 },
  { publisherName: 'Olívia Porto', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Solange Telles', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Explicando suas crenças', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Ana Paula Oliveira', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Edna Costa', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Marilene Queiroz', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: '', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Cântico 72', type: ParticipationType.CANTICO },
  { publisherName: 'Diego Fontana', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Como podemos apoiar o Reino de Deus de todo o coração?', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Israel Vieira', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Estudo bíblico de congregação', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Vitor Ramos', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Leitor do EBC', type: ParticipationType.LEITOR },
  { publisherName: 'Marcos Rogério', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Cântico 75', type: ParticipationType.CANTICO },
  { publisherName: 'Antônio Miguel', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  // DEZEMBRO 2024
  { publisherName: 'Diego Fontana', week: '2-8 de DEZ, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Diego Fontana', week: '2-8 de DEZ, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '2-8 de DEZ, 2024', partTitle: 'Cântico 127', type: ParticipationType.CANTICO },
  { publisherName: 'Marcos Vinícios', week: '2-8 de DEZ, 2024', partTitle: 'Como vou retribuir a Jeová?', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Alexsandro Lopes', week: '2-8 de DEZ, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Emerson França', week: '2-8 de DEZ, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Samuel Almeida', week: '2-8 de DEZ, 2024', partTitle: 'Franqueza — O que Jesus fez', type: ParticipationType.MINISTERIO, duration: 7 },
  { publisherName: 'Israel Vieira', week: '2-8 de DEZ, 2024', partTitle: 'Franqueza — Imite Jesus', type: ParticipationType.MINISTERIO, duration: 8 },
  { publisherName: '', week: '2-8 de DEZ, 2024', partTitle: 'Cântico 60', type: ParticipationType.CANTICO },
  { publisherName: 'Marcos Rogério', week: '2-8 de DEZ, 2024', partTitle: 'Necessidades locais', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Domingos Oliveira', week: '2-8 de DEZ, 2024', partTitle: 'Estudo bíblico de congregação', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Getúlio Rastoldo', week: '2-8 de DEZ, 2024', partTitle: 'Leitor do EBC', type: ParticipationType.LEITOR },
  { publisherName: 'Diego Fontana', week: '2-8 de DEZ, 2024', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '2-8 de DEZ, 2024', partTitle: 'Cântico 29', type: ParticipationType.CANTICO },
  { publisherName: 'Mário Porto', week: '2-8 de DEZ, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Israel Vieira', week: '9-15 de DEZ, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Israel Vieira', week: '9-15 de DEZ, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '9-15 de DEZ, 2024', partTitle: 'Cântico 124', type: ParticipationType.CANTICO },
  { publisherName: 'Alexsandro Lopes', week: '9-15 de DEZ, 2024', partTitle: '"Como um jovem pode manter puro o seu caminho?"', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Júnior Fouraux', week: '9-15 de DEZ, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Antônio Nascimento', week: '9-15 de DEZ, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Eliana Souza', week: '9-15 de DEZ, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Wanderleia Santos', week: '9-15 de DEZ, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Elza Elena', week: '9-15 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'José Luiz Fouraux', week: '9-15 de DEZ, 2024', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: '', week: '9-15 de DEZ, 2024', partTitle: 'Cântico 40', type: ParticipationType.CANTICO },
  { publisherName: 'Gabriel Camilo', week: '9-15 de DEZ, 2024', partTitle: 'Realizações da Organização de dezembro', type: ParticipationType.VIDA_CRISTA, duration: 10 },
  { publisherName: 'Marcos Rogério', week: '9-15 de DEZ, 2024', partTitle: 'Estudo bíblico de congregação', type: ParticipationType.DIRIGENTE, duration: 29 },
  { publisherName: 'Gabriel Camilo', week: '9-15 de DEZ, 2024', partTitle: 'Leitor do EBC', type: ParticipationType.LEITOR },
  { publisherName: 'Israel Vieira', week: '9-15 de DEZ, 2024', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '9-15 de DEZ, 2024', partTitle: 'Cântico 21', type: ParticipationType.CANTICO },
  { publisherName: 'Júnior Fouraux', week: '9-15 de DEZ, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Edmardo Queiroz', week: '16-22 de DEZ, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Edmardo Queiroz', week: '16-22 de DEZ, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '16-22 de DEZ, 2024', partTitle: 'Cântico 129', type: ParticipationType.CANTICO },
  { publisherName: 'Juberto Santos', week: '16-22 de DEZ, 2024', partTitle: 'Como perseverar diante de dificuldades', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'José Luiz Fouraux', week: '16-22 de DEZ, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Daniel Silva', week: '16-22 de DEZ, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Terezinha Oliveira', week: '16-22 de DEZ, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Débora Cristine', week: '16-22 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Vitoria Emanuelle', week: '16-22 de DEZ, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Dayse Campos', week: '16-22 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Waleska Nascimento', week: '16-22 de DEZ, 2024', partTitle: 'Explicando suas crenças', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Ágatha do Nascimento', week: '16-22 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: '', week: '16-22 de DEZ, 2024', partTitle: 'Cântico 128', type: ParticipationType.CANTICO },
  { publisherName: 'Renato Oliveira', week: '16-22 de DEZ, 2024', partTitle: 'Jeová nos ajuda a perseverar', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Marcos Vinícios', week: '16-22 de DEZ, 2024', partTitle: 'Estudo bíblico de congregação', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Felipe Oliveira', week: '16-22 de DEZ, 2024', partTitle: 'Leitor do EBC', type: ParticipationType.LEITOR },
  { publisherName: 'Edmardo Queiroz', week: '16-22 de DEZ, 2024', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '16-22 de DEZ, 2024', partTitle: 'Cântico 32', type: ParticipationType.CANTICO },
  { publisherName: 'Renato Oliveira', week: '16-22 de DEZ, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Renato Oliveira', week: '23-29 de DEZ, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Renato Oliveira', week: '23-29 de DEZ, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '23-29 de DEZ, 2024', partTitle: 'Cântico 31', type: ParticipationType.CANTICO },
  { publisherName: 'Marcos Rogério', week: '23-29 de DEZ, 2024', partTitle: 'Como evitar sofrimento desnecessário', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Emerson Souza', week: '23-29 de DEZ, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'João Paulo', week: '23-29 de DEZ, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Ana Paula', week: '23-29 de DEZ, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Tainá Reis', week: '23-29 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Ariane Bello', week: '23-29 de DEZ, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Ágatha Nascimento', week: '23-29 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Érika Segall', week: '23-29 de DEZ, 2024', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Terezinha Oliveira', week: '23-29 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: '', week: '23-29 de DEZ, 2024', partTitle: 'Cântico 121', type: ParticipationType.CANTICO },
  { publisherName: 'Eliezer Rosa', week: '23-29 de DEZ, 2024', partTitle: 'Não deixe o dinheiro fazer você sofrer desnecessariamente', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Edmardo Queiroz', week: '23-29 de DEZ, 2024', partTitle: 'Estudo bíblico de congregação', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Erick José', week: '23-29 de DEZ, 2024', partTitle: 'Leitor do EBC', type: ParticipationType.LEITOR },
  { publisherName: 'Renato Oliveira', week: '23-29 de DEZ, 2024', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '23-29 de DEZ, 2024', partTitle: 'Cântico 101', type: ParticipationType.CANTICO },
  { publisherName: 'Erick José', week: '23-29 de DEZ, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  // DEZ 2024 / JAN 2025
  { publisherName: 'Eliezer Rosa', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Eliezer Rosa', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Cântico 144', type: ParticipationType.CANTICO },
  { publisherName: 'Diego Fontana', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Eles semearam com lágrimas, mas colheram com alegria', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Alexsandro Lopes', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Gabriel Fouraux', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Ágatha Nascimento', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Malena Colangero', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Auxiliadora Valéria', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Michele Camillo', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Eliana Souza', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Neuza Campanha', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: '', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Cântico 155', type: ParticipationType.CANTICO },
  { publisherName: 'Juberto Santos', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Alegre-se com as promessas de Deus', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Renato Oliveira', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Estudo bíblico de congregação', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Victor Correa', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Leitor do EBC', type: ParticipationType.LEITOR },
  { publisherName: 'Eliezer Rosa', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Cântico 58', type: ParticipationType.CANTICO },
  { publisherName: 'Alexsandro Lopes', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  // DEZEMBRO 2025 (do anexo mais antigo)
  { publisherName: 'Marcos Vinícios', week: '1-7 de DEZ, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Marcos Vinícios', week: '1-7 de DEZ, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '1-7 de DEZ, 2025', partTitle: 'Cântico 135', type: ParticipationType.CANTICO },
  { publisherName: 'Renato Oliveira', week: '1-7 de DEZ, 2025', partTitle: 'Jeová merecia e esperava obediência do seu povo', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'José Luiz Fouraux', week: '1-7 de DEZ, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Gérson Santos', week: '1-7 de DEZ, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Yngrid França', week: '1-7 de DEZ, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Keyla Costa', week: '1-7 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Jacyra Eugênio', week: '1-7 de DEZ, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Vitoria Emanuelle', week: '1-7 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Ana Paula Oliveira', week: '1-7 de DEZ, 2025', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Ágatha Nascimento', week: '1-7 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: '', week: '1-7 de DEZ, 2025', partTitle: 'Cântico 65', type: ParticipationType.CANTICO },
  { publisherName: 'Edmardo Queiroz', week: '1-7 de DEZ, 2025', partTitle: 'Necessidades locais', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Israel Vieira', week: '1-7 de DEZ, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Júnior Fouraux', week: '1-7 de DEZ, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Marcos Vinícios', week: '1-7 de DEZ, 2025', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '1-7 de DEZ, 2025', partTitle: 'Cântico 4', type: ParticipationType.CANTICO },
  { publisherName: 'André Luiz', week: '1-7 de DEZ, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Diego Fontana', week: '8-14 de DEZ, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Diego Fontana', week: '8-14 de DEZ, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: '', week: '8-14 de DEZ, 2025', partTitle: 'Cântico 75', type: ParticipationType.CANTICO },
  { publisherName: 'Emerson Souza', week: '8-14 de DEZ, 2025', partTitle: '"Aqui estou! Envia-me!"', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Edmilson Monteiro', week: '8-14 de DEZ, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Vitor Correa', week: '8-14 de DEZ, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Suellen Correa', week: '8-14 de DEZ, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Julianne Cravo Figueredo', week: '8-14 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Marilene Queiroz', week: '8-14 de DEZ, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Terezinha Oliveira', week: '8-14 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Daniel Silva', week: '8-14 de DEZ, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Samuel Almeida', week: '8-14 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: '', week: '8-14 de DEZ, 2025', partTitle: 'Cântico 83', type: ParticipationType.CANTICO },
  { publisherName: 'Marcos Rogério', week: '8-14 de DEZ, 2025', partTitle: 'Pregação de casa em casa — nossa marca registrada', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Edmardo Queiroz', week: '8-14 de DEZ, 2025', partTitle: 'Estudo bíblico de congregação', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Eryck Segal', week: '8-14 de DEZ, 2025', partTitle: 'Leitor do EBC', type: ParticipationType.LEITOR },
  { publisherName: 'Diego Fontana', week: '8-14 de DEZ, 2025', partTitle: 'Comentários Finais', type: ParticipationType.COMENTARIOS_FINAIS },
  { publisherName: '', week: '8-14 de DEZ, 2025', partTitle: 'Cântico', type: ParticipationType.CANTICO },
  { publisherName: 'João Marcos P. Costa (SC)', week: '8-14 de DEZ, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },
];

export const initialParticipations: Participation[] = rawParticipations.map(p => ({
    ...p,
    id: generateUUID(),
    date: calculatePartDate(p.week),
}));